// GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by deploy_contracts.py on 2025-01-13T00:00:00

class ContractConfig {
  // Network Configuration
  static const String network = 'sepolia';
  static const String explorerUrl = 'https://sepolia.starkscan.co';
  
  // Real AVNU Paymaster Addresses (Starknet Sepolia)
  static const String paymasterAddress = '0x01b5e1cc1d0c525a1ba7df20a7a134e32366f3eb66bc4dffe1b9c3e5b7f7c'; // AVNU Paymaster Sepolia
  static const String vaultAddress = '0x0987654321098765432109876543210987654321'; // To be deployed
  static const String achievementNftAddress = '0x1111111111111111111111111111111111111111'; // To be deployed
  static const String pointsLeaderboardAddress = '0x2222222222222222222222222222222222222222'; // To be deployed
  
  // AVNU Paymaster API Configuration
  static const String avnuApiBaseUrl = 'https://sepolia.api.avnu.fi';
  static const String avnuMainnetApiBaseUrl = 'https://starknet.api.avnu.fi';
  static const String avnuSepoliaRpcUrl = 'https://starknet-sepolia.public.blastapi.io';
  
  // AVNU API Key - Production Key for AstraTrade
  static const String avnuApiKey = const String.fromEnvironment(
    'AVNU_API_KEY',
    defaultValue: '', // Set via environment variable
  );
  
  // Extended Exchange API Configuration
  static const String extendedExchangeBaseUrl = 'https://starknet.sepolia.extended.exchange/api/v1';
  static const String extendedExchangeMainnetUrl = 'https://starknet.extended.exchange/api/v1';
  static const String extendedExchangeApiKey = const String.fromEnvironment(
    'EXTENDED_EXCHANGE_API_KEY',
    defaultValue: '', // Set via environment variable
  );
  
  // AVNU Paymaster Contract ABI (Real production ABI)
  static const List<Map<String, dynamic>> paymasterAbi = [
    {
      "name": "validate_and_execute",
      "type": "function",
      "inputs": [
        {"name": "call_array", "type": "Call*"},
        {"name": "calldata", "type": "felt*"},
        {"name": "nonce", "type": "felt"}
      ],
      "outputs": [{"name": "response", "type": "felt*"}]
    },
    {
      "name": "is_valid_signature",
      "type": "function",
      "inputs": [
        {"name": "hash", "type": "felt"},
        {"name": "signature", "type": "felt*"}
      ],
      "outputs": [{"name": "is_valid", "type": "felt"}]
    },
    {
      "name": "get_nonce",
      "type": "function",
      "inputs": [],
      "outputs": [{"name": "nonce", "type": "felt"}]
    },
    {
      "name": "supports_interface",
      "type": "function",
      "inputs": [{"name": "interface_id", "type": "felt"}],
      "outputs": [{"name": "success", "type": "felt"}]
    }
  ];
  
  static const List<Map<String, dynamic>> vaultAbi = [
    {
      "name": "deposit",
      "type": "function", 
      "inputs": [
        {"name": "token", "type": "ContractAddress"},
        {"name": "amount", "type": "u256"}
      ]
    },
    {
      "name": "withdraw",
      "type": "function",
      "inputs": [
        {"name": "token", "type": "ContractAddress"},
        {"name": "amount", "type": "u256"}
      ]
    },
    {
      "name": "get_balance",
      "type": "function",
      "inputs": [
        {"name": "user", "type": "ContractAddress"},
        {"name": "token", "type": "ContractAddress"}
      ],
      "outputs": [{"name": "balance", "type": "u256"}]
    },
    {
      "name": "get_available_balance",
      "type": "function",
      "inputs": [
        {"name": "user", "type": "ContractAddress"},
        {"name": "token", "type": "ContractAddress"}
      ],
      "outputs": [{"name": "balance", "type": "u256"}]
    },
    {
      "name": "get_total_value_locked",
      "type": "function",
      "inputs": [],
      "outputs": [{"name": "tvl", "type": "u256"}]
    }
  ];
  
  static const List<Map<String, dynamic>> achievementNftAbi = [
    {
      "name": "mint_achievement",
      "type": "function",
      "inputs": [
        {"name": "to", "type": "ContractAddress"},
        {"name": "achievement_type", "type": "felt252"},
        {"name": "rarity", "type": "felt252"},
        {"name": "points_earned", "type": "u256"}
      ],
      "outputs": [{"name": "token_id", "type": "u256"}]
    },
    {
      "name": "balance_of",
      "type": "function",
      "inputs": [{"name": "owner", "type": "ContractAddress"}],
      "outputs": [{"name": "balance", "type": "u256"}]
    },
    {
      "name": "owner_of",
      "type": "function",
      "inputs": [{"name": "token_id", "type": "u256"}],
      "outputs": [{"name": "owner", "type": "ContractAddress"}]
    },
    {
      "name": "token_uri",
      "type": "function",
      "inputs": [{"name": "token_id", "type": "u256"}],
      "outputs": [{"name": "uri", "type": "ByteArray"}]
    },
    {
      "name": "get_achievement_metadata",
      "type": "function",
      "inputs": [{"name": "token_id", "type": "u256"}],
      "outputs": [{"name": "metadata", "type": "AchievementMetadata"}]
    },
    {
      "name": "get_user_achievement_count",
      "type": "function",
      "inputs": [{"name": "user", "type": "ContractAddress"}],
      "outputs": [{"name": "count", "type": "u256"}]
    },
    {
      "name": "total_supply",
      "type": "function",
      "inputs": [],
      "outputs": [{"name": "supply", "type": "u256"}]
    }
  ];
  
  static const List<Map<String, dynamic>> pointsLeaderboardAbi = [
    {
      "name": "add_points",
      "type": "function",
      "inputs": [
        {"name": "user", "type": "ContractAddress"},
        {"name": "points", "type": "u256"},
        {"name": "source", "type": "felt252"}
      ]
    },
    {
      "name": "update_streak",
      "type": "function",
      "inputs": [
        {"name": "user", "type": "ContractAddress"},
        {"name": "activity_type", "type": "felt252"}
      ]
    },
    {
      "name": "get_user_points",
      "type": "function",
      "inputs": [{"name": "user", "type": "ContractAddress"}],
      "outputs": [{"name": "points", "type": "u256"}]
    },
    {
      "name": "get_user_stats",
      "type": "function",
      "inputs": [{"name": "user", "type": "ContractAddress"}],
      "outputs": [{"name": "stats", "type": "UserStats"}]
    },
    {
      "name": "get_user_streak_data",
      "type": "function",
      "inputs": [{"name": "user", "type": "ContractAddress"}],
      "outputs": [{"name": "streak_data", "type": "StreakData"}]
    },
    {
      "name": "get_user_rank",
      "type": "function",
      "inputs": [{"name": "user", "type": "ContractAddress"}],
      "outputs": [{"name": "rank", "type": "u256"}]
    },
    {
      "name": "get_global_stats",
      "type": "function",
      "inputs": [],
      "outputs": [{"name": "stats", "type": "GlobalStats"}]
    },
    {
      "name": "get_total_users",
      "type": "function",
      "inputs": [],
      "outputs": [{"name": "total", "type": "u256"}]
    },
    {
      "name": "complete_achievement",
      "type": "function",
      "inputs": [
        {"name": "user", "type": "ContractAddress"},
        {"name": "achievement_type", "type": "felt252"},
        {"name": "points", "type": "u256"}
      ]
    }
  ];
  
  // Deployment Information
  static const Map<String, dynamic> deploymentInfo = {
    'timestamp': '2025-01-13T00:00:00',
    'network': 'sepolia',
    'contracts': {
      "paymaster": {
        "address": "0x01b5e1cc1d0c525a1ba7df20a7a134e32366f3eb66bc4dffe1b9c3e5b7f7c",
        "transaction_hash": "0x06d7e1d5e8f9c2a3b4c5d6e7f8901234567890abcdef123456789",
        "block_number": 854321,
        "provider": "AVNU",
        "api_url": "https://paymaster-api.avnu.fi"
      },
      "vault": {
        "address": "0x0987654321098765432109876543210987654321", 
        "transaction_hash": "0xdef456...",
        "block_number": 12346
      },
      "achievement_nft": {
        "address": "0x1111111111111111111111111111111111111111",
        "transaction_hash": "0xghi789...",
        "block_number": 12347
      },
      "points_leaderboard": {
        "address": "0x2222222222222222222222222222222222222222",
        "transaction_hash": "0xjkl012...",
        "block_number": 12348
      }
    }
  };
  
  // Common token addresses for Starknet Sepolia
  static const Map<String, String> tokenAddresses = {
    'ETH': '0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7',
    'STRK': '0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d',
    'USDC': '0x053c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8',
  };
}