"""Create event_outbox table

Revision ID: 001
Revises: 
Create Date: 2025-08-04 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_outbox',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('aggregate_id', sa.String(), nullable=False),
        sa.Column('event_type', sa.String(), nullable=False),
        sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('priority', sa.Integer(), nullable=False, default=0),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_outbox_status', 'event_outbox', ['status'], unique=False)
    op.create_index('ix_event_outbox_created_at', 'event_outbox', ['created_at'], unique=False)
    op.create_index('ix_event_outbox_priority', 'event_outbox', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_event_outbox_priority', table_name='event_outbox')
    op.drop_index('ix_event_outbox_created_at', table_name='event_outbox')
    op.drop_index('ix_event_outbox_status', table_name='event_outbox')
    op.drop_table('event_outbox')
    # ### end Alembic commands ###